UPDATE public.students SET nisn = '009700001', updated_at = NOW() WHERE full_name = 'ABIDZAR PUTRA YOGI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700002', updated_at = NOW() WHERE full_name = 'ABIYYU EMIRUL KHAIR' AND class_name = '7E';
UPDATE public.students SET nisn = '009700003', updated_at = NOW() WHERE full_name = 'ACQUILA AZZALEA QISYA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700004', updated_at = NOW() WHERE full_name = 'AFIQA HAMIDAH' AND class_name = '7E';
UPDATE public.students SET nisn = '009700005', updated_at = NOW() WHERE full_name = 'ALPIAN MUHAMAD RAPA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700006', updated_at = NOW() WHERE full_name = 'ANINDIA RABIA PUTRI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700007', updated_at = NOW() WHERE full_name = 'AQILA AZIZATUL FADHLA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700008', updated_at = NOW() WHERE full_name = 'ARAFAH PUTRAYANA ADITYA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700009', updated_at = NOW() WHERE full_name = 'ARJUNA PRATAMA AKBAR' AND class_name = '7E';
UPDATE public.students SET nisn = '009700010', updated_at = NOW() WHERE full_name = 'AYESHA HEBA ASSYAKIRA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700011', updated_at = NOW() WHERE full_name = 'AZKA MAULANA ARRAIHAN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700012', updated_at = NOW() WHERE full_name = 'CAPRILIA XANZA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700013', updated_at = NOW() WHERE full_name = 'CINTA NAURA SECHAN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700014', updated_at = NOW() WHERE full_name = 'DARPATUL LAILA RAHMADANI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700015', updated_at = NOW() WHERE full_name = 'DIMAS PRASONGKO' AND class_name = '7E';
UPDATE public.students SET nisn = '009700016', updated_at = NOW() WHERE full_name = 'FADYA ASSYIFA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700017', updated_at = NOW() WHERE full_name = 'HAMDUN ABDUL KARIM' AND class_name = '7E';
UPDATE public.students SET nisn = '009700018', updated_at = NOW() WHERE full_name = 'IFFA ASTILA RAHMA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700019', updated_at = NOW() WHERE full_name = 'KHANZA SHAZIA RIFA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700020', updated_at = NOW() WHERE full_name = 'KHAYURA ASYABIYA RAHMAN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700021', updated_at = NOW() WHERE full_name = 'KHOIRUNISA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700022', updated_at = NOW() WHERE full_name = 'MUHAMAD FILAN BAIHAKI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700023', updated_at = NOW() WHERE full_name = 'MUHAMAD REHAN ARIYAN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700024', updated_at = NOW() WHERE full_name = 'MUHAMAD RIZKY AL-QOWI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700025', updated_at = NOW() WHERE full_name = 'MUHAMMAD AFKAR ALQISTHI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700026', updated_at = NOW() WHERE full_name = 'MUHAMMAD AKMAL FALLAH' AND class_name = '7E';
UPDATE public.students SET nisn = '009700027', updated_at = NOW() WHERE full_name = 'MUHAMMAD DIRGHAM HAIDAR NUGRAHA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700028', updated_at = NOW() WHERE full_name = 'MUHAMMAD RIZKY MAULANA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700029', updated_at = NOW() WHERE full_name = 'MUHAMMAD SAUGI AL-GHIFARI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700030', updated_at = NOW() WHERE full_name = 'NAJWA A''ISYATUL AFIFAH' AND class_name = '7E';
UPDATE public.students SET nisn = '009700031', updated_at = NOW() WHERE full_name = 'NASYAH AGUSTINA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700032', updated_at = NOW() WHERE full_name = 'NAURA NADHIFA MALADI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700033', updated_at = NOW() WHERE full_name = 'NAYLA NEHAYATUL KAMILAH' AND class_name = '7E';
UPDATE public.students SET nisn = '009700034', updated_at = NOW() WHERE full_name = 'PARULIAN LEE SIAHAAN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700035', updated_at = NOW() WHERE full_name = 'RAIHAN ALFA RISKI' AND class_name = '7E';
UPDATE public.students SET nisn = '009700036', updated_at = NOW() WHERE full_name = 'RIANGGUN HAERUTAMA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700037', updated_at = NOW() WHERE full_name = 'RIKO DUTA DAMARA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700038', updated_at = NOW() WHERE full_name = 'SABINA AYLA QAIREEN' AND class_name = '7E';
UPDATE public.students SET nisn = '009700039', updated_at = NOW() WHERE full_name = 'SIPA ALISA AJAHRA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700040', updated_at = NOW() WHERE full_name = 'ZIANDRA NAZMU NUGRAHA' AND class_name = '7E';
UPDATE public.students SET nisn = '009700041', updated_at = NOW() WHERE full_name = 'AKHMAD JEN' AND class_name = '7F';
UPDATE public.students SET nisn = '009700042', updated_at = NOW() WHERE full_name = 'AKILLA DESFINDA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700043', updated_at = NOW() WHERE full_name = 'AKSA ALHAFIZH MARGONO' AND class_name = '7F';
UPDATE public.students SET nisn = '009700044', updated_at = NOW() WHERE full_name = 'AMARA NABILA ZAKIA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700045', updated_at = NOW() WHERE full_name = 'ANGEL HABIBAH' AND class_name = '7F';
UPDATE public.students SET nisn = '009700046', updated_at = NOW() WHERE full_name = 'AQILA SASABILA RAMADHANI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700047', updated_at = NOW() WHERE full_name = 'AULIYA ARISTA FIRDIYANA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700048', updated_at = NOW() WHERE full_name = 'AZKHA MAULANA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700049', updated_at = NOW() WHERE full_name = 'BILQIS UFAIRA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700050', updated_at = NOW() WHERE full_name = 'CANTIKA KAYLA PUTRI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700051', updated_at = NOW() WHERE full_name = 'DIKI MAULANA FAUZAN' AND class_name = '7F';
UPDATE public.students SET nisn = '009700052', updated_at = NOW() WHERE full_name = 'DZAKI SURYA MAHESA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700053', updated_at = NOW() WHERE full_name = 'ERINDA FAZYLA SUSANTO' AND class_name = '7F';
UPDATE public.students SET nisn = '009700054', updated_at = NOW() WHERE full_name = 'FAIQ RAFIQI NURA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700055', updated_at = NOW() WHERE full_name = 'FARHAN SEPTIYANI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700056', updated_at = NOW() WHERE full_name = 'FARIZ NAUFAL RAHARDIAN' AND class_name = '7F';
UPDATE public.students SET nisn = '009700057', updated_at = NOW() WHERE full_name = 'FAUZIYAH' AND class_name = '7F';
UPDATE public.students SET nisn = '009700058', updated_at = NOW() WHERE full_name = 'HANIFAIHA RAMADHANI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700059', updated_at = NOW() WHERE full_name = 'HANY RIZKIYA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700060', updated_at = NOW() WHERE full_name = 'KENZY ASSYIFA MAGHDALENA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700061', updated_at = NOW() WHERE full_name = 'M.ZHILDAN RAMADHAN' AND class_name = '7F';
UPDATE public.students SET nisn = '009700062', updated_at = NOW() WHERE full_name = 'MEISHADIVIA SANTOSO' AND class_name = '7F';
UPDATE public.students SET nisn = '009700063', updated_at = NOW() WHERE full_name = 'MUHAMMAD AQLAN RHOMDONY' AND class_name = '7F';
UPDATE public.students SET nisn = '009700064', updated_at = NOW() WHERE full_name = 'MUHAMMAD AZZAM MAJIID SANTOSO' AND class_name = '7F';
UPDATE public.students SET nisn = '009700065', updated_at = NOW() WHERE full_name = 'MUHAMMAD FATHIR MAULANA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700066', updated_at = NOW() WHERE full_name = 'MUHAMMAD FATIR AS-SYAQIR' AND class_name = '7F';
UPDATE public.students SET nisn = '009700067', updated_at = NOW() WHERE full_name = 'MUHAMMAD HASURI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700068', updated_at = NOW() WHERE full_name = 'MUHAMMAD JABIL RUSYAIDI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700069', updated_at = NOW() WHERE full_name = 'MUHAMMAD JULIANSAH' AND class_name = '7F';
UPDATE public.students SET nisn = '009700070', updated_at = NOW() WHERE full_name = 'MUHAMMAD SYUJA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700071', updated_at = NOW() WHERE full_name = 'NAURA SHAFWAN MASITA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700072', updated_at = NOW() WHERE full_name = 'RAFELLA RAISHA' AND class_name = '7F';
UPDATE public.students SET nisn = '009700073', updated_at = NOW() WHERE full_name = 'RATU ADZKIARA VAHLEVI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700074', updated_at = NOW() WHERE full_name = 'RATU NAFISAH ELZHAR' AND class_name = '7F';
UPDATE public.students SET nisn = '009700075', updated_at = NOW() WHERE full_name = 'RIFAL AKBAR' AND class_name = '7F';
UPDATE public.students SET nisn = '009700076', updated_at = NOW() WHERE full_name = 'RISKA RAMADANI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700077', updated_at = NOW() WHERE full_name = 'ROBIATUL ADAWIYAH APDI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700078', updated_at = NOW() WHERE full_name = 'SALSA NABILA JUANDINI' AND class_name = '7F';
UPDATE public.students SET nisn = '009700079', updated_at = NOW() WHERE full_name = 'SANDY' AND class_name = '7F';
UPDATE public.students SET nisn = '009700080', updated_at = NOW() WHERE full_name = 'SATRIO SANTOSO' AND class_name = '7F';
UPDATE public.students SET nisn = '009900081', updated_at = NOW() WHERE full_name = 'ABDUL SAHID' AND class_name = '9E';
UPDATE public.students SET nisn = '009900082', updated_at = NOW() WHERE full_name = 'AHMAD FAUZAN SHOFA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900083', updated_at = NOW() WHERE full_name = 'AHMAD SABIL AUFA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900084', updated_at = NOW() WHERE full_name = 'ALISHBA NAYYARA FILZAH' AND class_name = '9E';
UPDATE public.students SET nisn = '009900085', updated_at = NOW() WHERE full_name = 'ARYA DZAKY NATAKUSUMAH' AND class_name = '9E';
UPDATE public.students SET nisn = '009900086', updated_at = NOW() WHERE full_name = 'ATIKAH RAMADANI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900087', updated_at = NOW() WHERE full_name = 'AZWAN SYAHRIL FAUJI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900088', updated_at = NOW() WHERE full_name = 'BILAL ATHAR' AND class_name = '9E';
UPDATE public.students SET nisn = '009900089', updated_at = NOW() WHERE full_name = 'CHARISSA GALUH BACHTIAR' AND class_name = '9E';
UPDATE public.students SET nisn = '009900090', updated_at = NOW() WHERE full_name = 'DANI ARDIANSYAH' AND class_name = '9E';
UPDATE public.students SET nisn = '009900091', updated_at = NOW() WHERE full_name = 'FAHRY AHMAD' AND class_name = '9E';
UPDATE public.students SET nisn = '009900092', updated_at = NOW() WHERE full_name = 'FAQIH RAMADHAN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900093', updated_at = NOW() WHERE full_name = 'FAUZAN AVIAN MUNIR' AND class_name = '9E';
UPDATE public.students SET nisn = '009900094', updated_at = NOW() WHERE full_name = 'KHOLIFAH MEYLANI PUTRI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900095', updated_at = NOW() WHERE full_name = 'LINTANG NAGA CAESAR' AND class_name = '9E';
UPDATE public.students SET nisn = '009900096', updated_at = NOW() WHERE full_name = 'LISDA NINGSIH RAMADHANI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900097', updated_at = NOW() WHERE full_name = 'MUHAMAD FADHIL LUKMAN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900098', updated_at = NOW() WHERE full_name = 'MUHAMAD ILYAS DZULKARNAIN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900099', updated_at = NOW() WHERE full_name = 'MUHAMAD WILDAN SEBASTIAN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900100', updated_at = NOW() WHERE full_name = 'MUHAMMAD FARIS MULYAWAN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900101', updated_at = NOW() WHERE full_name = 'MUHAMMAD KHAIRUL FAHMI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900102', updated_at = NOW() WHERE full_name = 'MUHAMMAD MIRZA ARIFIN' AND class_name = '9E';
UPDATE public.students SET nisn = '009900103', updated_at = NOW() WHERE full_name = 'MUHAMMAD RADITHYA PRATAMA RONIE' AND class_name = '9E';
UPDATE public.students SET nisn = '009900104', updated_at = NOW() WHERE full_name = 'MUHAMMAD RAFLY MAULANA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900105', updated_at = NOW() WHERE full_name = 'NAURA BELLA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900106', updated_at = NOW() WHERE full_name = 'NISA ULPA DILA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900107', updated_at = NOW() WHERE full_name = 'NOVA AZZAHRA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900108', updated_at = NOW() WHERE full_name = 'RAMA FAHRURROZI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900109', updated_at = NOW() WHERE full_name = 'RATU PARAMITA ANANTA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900110', updated_at = NOW() WHERE full_name = 'RAYA RIZQINA RAMADHANI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900111', updated_at = NOW() WHERE full_name = 'RENAFA DWI CAHYANI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900112', updated_at = NOW() WHERE full_name = 'RIFDA MUHNINA PUTRI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900113', updated_at = NOW() WHERE full_name = 'SADIRA KASYIFAQILA TRIADI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900114', updated_at = NOW() WHERE full_name = 'SALLY KIRANA APRILIA SIREGAR' AND class_name = '9E';
UPDATE public.students SET nisn = '009900115', updated_at = NOW() WHERE full_name = 'SHAVA AULIA WAHYUDI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900116', updated_at = NOW() WHERE full_name = 'SINTA SEFTIANI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900117', updated_at = NOW() WHERE full_name = 'SYIFA MAULIDATUL FITRIA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900118', updated_at = NOW() WHERE full_name = 'TUBAGUS FAEYZA MAJID' AND class_name = '9E';
UPDATE public.students SET nisn = '009900119', updated_at = NOW() WHERE full_name = 'YOLANDA FITRIA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900120', updated_at = NOW() WHERE full_name = 'YULIANA SUCI WULANDARI' AND class_name = '9E';
UPDATE public.students SET nisn = '009900121', updated_at = NOW() WHERE full_name = 'AULIA FAUZIAH' AND class_name = '9E';
UPDATE public.students SET nisn = '009900122', updated_at = NOW() WHERE full_name = 'DARRY PUTRA DIGDAYA' AND class_name = '9E';
UPDATE public.students SET nisn = '009900123', updated_at = NOW() WHERE full_name = 'AHYA''I AMWATULLAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900124', updated_at = NOW() WHERE full_name = 'ALIYA DITA ZAFIRA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900125', updated_at = NOW() WHERE full_name = 'AMIRA TYAS MARGONO' AND class_name = '9F';
UPDATE public.students SET nisn = '009900126', updated_at = NOW() WHERE full_name = 'ARJUNA MAHARDIKA PRATAMA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900127', updated_at = NOW() WHERE full_name = 'AZZAHNY PUTRI HERMAWAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900128', updated_at = NOW() WHERE full_name = 'BRIAND JABBAR NOVANTO' AND class_name = '9F';
UPDATE public.students SET nisn = '009900129', updated_at = NOW() WHERE full_name = 'DESWITA OKTADINA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900130', updated_at = NOW() WHERE full_name = 'EKA SULPATRI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900131', updated_at = NOW() WHERE full_name = 'FATURROHMAN SYAPUTRA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900132', updated_at = NOW() WHERE full_name = 'FERDY ADITIYA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900133', updated_at = NOW() WHERE full_name = 'GALVIN ZAKY PRANIANSYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900134', updated_at = NOW() WHERE full_name = 'GINAA AAFIYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900135', updated_at = NOW() WHERE full_name = 'HASINA NAYYARA AL GHOJALI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900136', updated_at = NOW() WHERE full_name = 'JAHROTUN NAKIYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900137', updated_at = NOW() WHERE full_name = 'KANZA MAYDINA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900138', updated_at = NOW() WHERE full_name = 'KAYLA UDZMA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900139', updated_at = NOW() WHERE full_name = 'KHOIRUL DWIANJAYA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900140', updated_at = NOW() WHERE full_name = 'LIA AULIA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900141', updated_at = NOW() WHERE full_name = 'LUSI AGUSTINA RHAMADANI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900142', updated_at = NOW() WHERE full_name = 'MAS ANANDA AZRIE MAULANA R' AND class_name = '9F';
UPDATE public.students SET nisn = '009900143', updated_at = NOW() WHERE full_name = 'MAULIDIYA ASSIFA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900144', updated_at = NOW() WHERE full_name = 'MOHAMMAD FAKHRI AZHAR' AND class_name = '9F';
UPDATE public.students SET nisn = '009900145', updated_at = NOW() WHERE full_name = 'MUHAMAD MAHESA AL-FIZAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900146', updated_at = NOW() WHERE full_name = 'MUHAMAD RHEZA RAMADHAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900147', updated_at = NOW() WHERE full_name = 'MUHAMMAD RIZKY RAMADAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900148', updated_at = NOW() WHERE full_name = 'NAURA SESILIA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900149', updated_at = NOW() WHERE full_name = 'NESSYA FAHIRA MEGA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900150', updated_at = NOW() WHERE full_name = 'NUR HIKMAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900151', updated_at = NOW() WHERE full_name = 'OLIVIA DARA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900152', updated_at = NOW() WHERE full_name = 'PUTRI RAHAYU' AND class_name = '9F';
UPDATE public.students SET nisn = '009900153', updated_at = NOW() WHERE full_name = 'RAEYA SAABIRA GUNAWAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900154', updated_at = NOW() WHERE full_name = 'RISKA NATALIA SIMARMATA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900155', updated_at = NOW() WHERE full_name = 'SALSABILA SUHANAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900156', updated_at = NOW() WHERE full_name = 'SEP RAHMAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900157', updated_at = NOW() WHERE full_name = 'SHIFA KHANSA AFIRA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900158', updated_at = NOW() WHERE full_name = 'SYAKIRA ALMIRA ZAHARANI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900159', updated_at = NOW() WHERE full_name = 'SYIFA CORDELIA RAFANI' AND class_name = '9F';
UPDATE public.students SET nisn = '009900160', updated_at = NOW() WHERE full_name = 'VANESHA NOVIANATA' AND class_name = '9F';
UPDATE public.students SET nisn = '009900161', updated_at = NOW() WHERE full_name = 'MUHAMMAD IZHAM ADRIANSYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900162', updated_at = NOW() WHERE full_name = 'ALMAY RAYYAN RUBY FALAH' AND class_name = '9F';
UPDATE public.students SET nisn = '009900163', updated_at = NOW() WHERE full_name = 'AL BAIHAQI MARTIAN' AND class_name = '9F';
UPDATE public.students SET nisn = '009900164', updated_at = NOW() WHERE full_name = 'ABDAN PARY' AND class_name = '9G';
UPDATE public.students SET nisn = '009900165', updated_at = NOW() WHERE full_name = 'ALLONA PUTRI ZANETA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900166', updated_at = NOW() WHERE full_name = 'ANDIKA RIZKI FIRDAUS' AND class_name = '9G';
UPDATE public.students SET nisn = '009900167', updated_at = NOW() WHERE full_name = 'ANISA RAMADANI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900168', updated_at = NOW() WHERE full_name = 'ASRA DIPA SURIYANTO' AND class_name = '9G';
UPDATE public.students SET nisn = '009900169', updated_at = NOW() WHERE full_name = 'CHESTER ABIA RACHMAD' AND class_name = '9G';
UPDATE public.students SET nisn = '009900170', updated_at = NOW() WHERE full_name = 'DHINA PUTRIANA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900171', updated_at = NOW() WHERE full_name = 'ELOISE MEGHAN PRANATA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900172', updated_at = NOW() WHERE full_name = 'FADHILAH AFZA NAIFA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900173', updated_at = NOW() WHERE full_name = 'FATIH ABDI BUDIMAN' AND class_name = '9G';
UPDATE public.students SET nisn = '009900174', updated_at = NOW() WHERE full_name = 'FAZILA BELVA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900175', updated_at = NOW() WHERE full_name = 'FRISKA AFISTA AULIA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900176', updated_at = NOW() WHERE full_name = 'HAYATI NUFUS' AND class_name = '9G';
UPDATE public.students SET nisn = '009900177', updated_at = NOW() WHERE full_name = 'JELITA ARYANTI PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900178', updated_at = NOW() WHERE full_name = 'KARUNIA EKA NINGSIH' AND class_name = '9G';
UPDATE public.students SET nisn = '009900179', updated_at = NOW() WHERE full_name = 'KEYLA AULIA PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900180', updated_at = NOW() WHERE full_name = 'LAILATUL QOMARIAH' AND class_name = '9G';
UPDATE public.students SET nisn = '009900181', updated_at = NOW() WHERE full_name = 'M. FEBRIYANSYAH' AND class_name = '9G';
UPDATE public.students SET nisn = '009900182', updated_at = NOW() WHERE full_name = 'MARSHA OKTAVIA LATIFANISA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900183', updated_at = NOW() WHERE full_name = 'MICHAELA AZKIA ISLAMADINA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900184', updated_at = NOW() WHERE full_name = 'MOH IKBAR FAAD' AND class_name = '9G';
UPDATE public.students SET nisn = '009900185', updated_at = NOW() WHERE full_name = 'MUHAMAD ADI FIRMANSYAH' AND class_name = '9G';
UPDATE public.students SET nisn = '009900186', updated_at = NOW() WHERE full_name = 'MUHAMAD RAPAEL' AND class_name = '9G';
UPDATE public.students SET nisn = '009900187', updated_at = NOW() WHERE full_name = 'MUHAMMAD IBNU AL-JABBAR' AND class_name = '9G';
UPDATE public.students SET nisn = '009900188', updated_at = NOW() WHERE full_name = 'MUHAMMAD IHWANUL KARIM' AND class_name = '9G';
UPDATE public.students SET nisn = '009900189', updated_at = NOW() WHERE full_name = 'NABIL ATHA SAKHI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900190', updated_at = NOW() WHERE full_name = 'NEYSA AYU DESTIANA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900191', updated_at = NOW() WHERE full_name = 'NIKEN APRILIANI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900192', updated_at = NOW() WHERE full_name = 'REGITA CAHYANI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900193', updated_at = NOW() WHERE full_name = 'RIZKI AL SEBASTIAN' AND class_name = '9G';
UPDATE public.students SET nisn = '009900194', updated_at = NOW() WHERE full_name = 'RIZKI MAULANA SOPIAN' AND class_name = '9G';
UPDATE public.students SET nisn = '009900195', updated_at = NOW() WHERE full_name = 'SANTI KURNIAWATI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900196', updated_at = NOW() WHERE full_name = 'SHAALIHUDDIN AL-AYUBI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900197', updated_at = NOW() WHERE full_name = 'SRI ULYATI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900198', updated_at = NOW() WHERE full_name = 'SYAUQI JALADARA PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900199', updated_at = NOW() WHERE full_name = 'TAHTA DHIKA SINATRIA' AND class_name = '9G';
UPDATE public.students SET nisn = '009900200', updated_at = NOW() WHERE full_name = 'VICKY REVALKA ALKHI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900201', updated_at = NOW() WHERE full_name = 'VONDRA KASIH RIZKIA DETHAN' AND class_name = '9G';
UPDATE public.students SET nisn = '009900202', updated_at = NOW() WHERE full_name = 'ZAHRA FITRIA SARI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900203', updated_at = NOW() WHERE full_name = 'DESTIANA SAPUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '009900204', updated_at = NOW() WHERE full_name = 'MUHAMAD RIDO' AND class_name = '9G';
UPDATE public.students SET nisn = '009900205', updated_at = NOW() WHERE full_name = 'ABDUL FAQRY' AND class_name = '9H';
UPDATE public.students SET nisn = '009900206', updated_at = NOW() WHERE full_name = 'ACHMAD FARIZKY' AND class_name = '9H';
UPDATE public.students SET nisn = '009900207', updated_at = NOW() WHERE full_name = 'AJENG PAMUNGKAS' AND class_name = '9H';
UPDATE public.students SET nisn = '009900208', updated_at = NOW() WHERE full_name = 'ALMIRA IRGI BILQIST' AND class_name = '9H';
UPDATE public.students SET nisn = '009900209', updated_at = NOW() WHERE full_name = 'ANDIKA GALANG RAMADHAN' AND class_name = '9H';
UPDATE public.students SET nisn = '009900210', updated_at = NOW() WHERE full_name = 'APRILIA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900211', updated_at = NOW() WHERE full_name = 'AQILNABIGH PUTRA RAHMAN' AND class_name = '9H';
UPDATE public.students SET nisn = '009900212', updated_at = NOW() WHERE full_name = 'ASYIFA RAMADHANI HAFID' AND class_name = '9H';
UPDATE public.students SET nisn = '009900213', updated_at = NOW() WHERE full_name = 'CITRA FAHIRA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900214', updated_at = NOW() WHERE full_name = 'DHINI PUTRIANI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900215', updated_at = NOW() WHERE full_name = 'ELVINA REZKYA P' AND class_name = '9H';
UPDATE public.students SET nisn = '009900216', updated_at = NOW() WHERE full_name = 'FATIMATUL ZAHRO' AND class_name = '9H';
UPDATE public.students SET nisn = '009900217', updated_at = NOW() WHERE full_name = 'FAUZUL AMARULLAH' AND class_name = '9H';
UPDATE public.students SET nisn = '009900218', updated_at = NOW() WHERE full_name = 'FEISYA AULIA ALMAS' AND class_name = '9H';
UPDATE public.students SET nisn = '009900219', updated_at = NOW() WHERE full_name = 'GANESH AZALIA GAYATRI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900220', updated_at = NOW() WHERE full_name = 'KALFAN DANAR IBRAHIM' AND class_name = '9H';
UPDATE public.students SET nisn = '009900221', updated_at = NOW() WHERE full_name = 'MANDALIKA CAHYA PUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900222', updated_at = NOW() WHERE full_name = 'MERLY MUTIARA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900223', updated_at = NOW() WHERE full_name = 'MOHAMAD RAFA EMERALDIANTO' AND class_name = '9H';
UPDATE public.students SET nisn = '009900224', updated_at = NOW() WHERE full_name = 'MUH RAFA RAMDANI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900225', updated_at = NOW() WHERE full_name = 'MUHAMAD AL GHAZALI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900226', updated_at = NOW() WHERE full_name = 'MUHAMAD FARHAN TRIDARMA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900227', updated_at = NOW() WHERE full_name = 'MUHAMAD KHA KURNIAWAN' AND class_name = '9H';
UPDATE public.students SET nisn = '009900228', updated_at = NOW() WHERE full_name = 'MUHAMAD RAFQI RAMADHAN' AND class_name = '9H';
UPDATE public.students SET nisn = '009900229', updated_at = NOW() WHERE full_name = 'MUHAMAD RAZKA IRSYA PRATAMA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900230', updated_at = NOW() WHERE full_name = 'MUHAMAD ZAKI ALHAFIDZ' AND class_name = '9H';
UPDATE public.students SET nisn = '009900231', updated_at = NOW() WHERE full_name = 'MUHAMMAD RAFA SAEFUL' AND class_name = '9H';
UPDATE public.students SET nisn = '009900232', updated_at = NOW() WHERE full_name = 'MUHAMMAD RICO ALFIAN' AND class_name = '9H';
UPDATE public.students SET nisn = '009900233', updated_at = NOW() WHERE full_name = 'NADHIRA RAYSA SARAH' AND class_name = '9H';
UPDATE public.students SET nisn = '009900234', updated_at = NOW() WHERE full_name = 'NAJWA ANANDA PUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900235', updated_at = NOW() WHERE full_name = 'NIVA NIRVANA ZAFIRA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900236', updated_at = NOW() WHERE full_name = 'PUTRI GENDIS NOVIAUTAMI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900237', updated_at = NOW() WHERE full_name = 'RATU AURELIA ANEIRA RAIHANAH' AND class_name = '9H';
UPDATE public.students SET nisn = '009900238', updated_at = NOW() WHERE full_name = 'RD.M SAID YUSUP' AND class_name = '9H';
UPDATE public.students SET nisn = '009900239', updated_at = NOW() WHERE full_name = 'RENADA HANIFAH' AND class_name = '9H';
UPDATE public.students SET nisn = '009900240', updated_at = NOW() WHERE full_name = 'RIFKI ADRIANSYAH' AND class_name = '9H';
UPDATE public.students SET nisn = '009900241', updated_at = NOW() WHERE full_name = 'SAFIRA ANGRAENI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900242', updated_at = NOW() WHERE full_name = 'SATRIA MAULANA' AND class_name = '9H';
UPDATE public.students SET nisn = '009900243', updated_at = NOW() WHERE full_name = 'SINTA WULAN SAPUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900244', updated_at = NOW() WHERE full_name = 'SUCI DWI PURWANTI' AND class_name = '9H';
UPDATE public.students SET nisn = '009900245', updated_at = NOW() WHERE full_name = 'TEDAS AWAN TANTULAR' AND class_name = '9H';
UPDATE public.students SET nisn = '009900246', updated_at = NOW() WHERE full_name = 'ZAHRA SEPTIANI PUTRI' AND class_name = '9H';