UPDATE public.students SET nisn = '0114298092', updated_at = NOW() WHERE full_name = 'ABDUL SAHID' AND class_name = '9E';
UPDATE public.students SET nisn = '0113947347', updated_at = NOW() WHERE full_name = 'AHMAD FAUZAN SHOFA' AND class_name = '9E';
UPDATE public.students SET nisn = '0117066303', updated_at = NOW() WHERE full_name = 'AHMAD SABIL AUFA' AND class_name = '9E';
UPDATE public.students SET nisn = '0122742361', updated_at = NOW() WHERE full_name = 'ALISHBA NAYYARA FILZAH' AND class_name = '9E';
UPDATE public.students SET nisn = '0127087227', updated_at = NOW() WHERE full_name = 'ARYA DZAKY NATAKUSUMAH' AND class_name = '9E';
UPDATE public.students SET nisn = '0112308014', updated_at = NOW() WHERE full_name = 'ATIKAH RAMADANI' AND class_name = '9E';
UPDATE public.students SET nisn = '0118396071', updated_at = NOW() WHERE full_name = 'AZWAN SYAHRIL FAUJI' AND class_name = '9E';
UPDATE public.students SET nisn = '0117392717', updated_at = NOW() WHERE full_name = 'BILAL ATHAR' AND class_name = '9E';
UPDATE public.students SET nisn = '0111827722', updated_at = NOW() WHERE full_name = 'CHARISSA GALUH BACHTIAR' AND class_name = '9E';
UPDATE public.students SET nisn = '0128215171', updated_at = NOW() WHERE full_name = 'DANI ARDIANSYAH' AND class_name = '9E';
UPDATE public.students SET nisn = '0122232608', updated_at = NOW() WHERE full_name = 'FAHRY AHMAD' AND class_name = '9E';
UPDATE public.students SET nisn = '0111924372', updated_at = NOW() WHERE full_name = 'FAQIH RAMADHAN' AND class_name = '9E';
UPDATE public.students SET nisn = '0129880030', updated_at = NOW() WHERE full_name = 'FAUZAN AVIAN MUNIR' AND class_name = '9E';
UPDATE public.students SET nisn = '0124745061', updated_at = NOW() WHERE full_name = 'KHOLIFAH MEYLANI PUTRI' AND class_name = '9E';
UPDATE public.students SET nisn = '0121652480', updated_at = NOW() WHERE full_name = 'LINTANG NAGA CAESAR' AND class_name = '9E';
UPDATE public.students SET nisn = '0122383286', updated_at = NOW() WHERE full_name = 'LISDA NINGSIH RAMADHANI' AND class_name = '9E';
UPDATE public.students SET nisn = '0112859566', updated_at = NOW() WHERE full_name = 'MUHAMAD FADHIL LUKMAN' AND class_name = '9E';
UPDATE public.students SET nisn = '3126546563', updated_at = NOW() WHERE full_name = 'MUHAMAD ILYAS DZULKARNAIN' AND class_name = '9E';
UPDATE public.students SET nisn = '0111185919', updated_at = NOW() WHERE full_name = 'MUHAMAD WILDAN SEBASTIAN' AND class_name = '9E';
UPDATE public.students SET nisn = '0112277011', updated_at = NOW() WHERE full_name = 'MUHAMMAD FARIS MULYAWAN' AND class_name = '9E';
UPDATE public.students SET nisn = '0112669759', updated_at = NOW() WHERE full_name = 'MUHAMMAD KHAIRUL FAHMI' AND class_name = '9E';
UPDATE public.students SET nisn = '3128542782', updated_at = NOW() WHERE full_name = 'MUHAMMAD MIRZA ARIFIN' AND class_name = '9E';
UPDATE public.students SET nisn = '0123328809', updated_at = NOW() WHERE full_name = 'MUHAMMAD RADITHYA PRATAMA RONIE' AND class_name = '9E';
UPDATE public.students SET nisn = '0124542360', updated_at = NOW() WHERE full_name = 'MUHAMMAD RAFLY MAULANA' AND class_name = '9E';
UPDATE public.students SET nisn = '0123664687', updated_at = NOW() WHERE full_name = 'NAURA BELLA' AND class_name = '9E';
UPDATE public.students SET nisn = '0128861324', updated_at = NOW() WHERE full_name = 'NISA ULPA DILA' AND class_name = '9E';
UPDATE public.students SET nisn = '0129455640', updated_at = NOW() WHERE full_name = 'NOVA AZZAHRA' AND class_name = '9E';
UPDATE public.students SET nisn = '0129234388', updated_at = NOW() WHERE full_name = 'RAMA FAHRURROZI' AND class_name = '9E';
UPDATE public.students SET nisn = '0122584723', updated_at = NOW() WHERE full_name = 'RATU PARAMITA ANANTA' AND class_name = '9E';
UPDATE public.students SET nisn = '0112571872', updated_at = NOW() WHERE full_name = 'RAYA RIZQINA RAMADHANI' AND class_name = '9E';
UPDATE public.students SET nisn = '0112260901', updated_at = NOW() WHERE full_name = 'RENAFA DWI CAHYANI' AND class_name = '9E';
UPDATE public.students SET nisn = '3129163406', updated_at = NOW() WHERE full_name = 'RIFDA MUHNINA PUTRI' AND class_name = '9E';
UPDATE public.students SET nisn = '0128479767', updated_at = NOW() WHERE full_name = 'SADIRA KASYIFAQILA TRIADI' AND class_name = '9E';
UPDATE public.students SET nisn = '0125282872', updated_at = NOW() WHERE full_name = 'SALLY KIRANA APRILIA SIREGAR' AND class_name = '9E';
UPDATE public.students SET nisn = '0115445399', updated_at = NOW() WHERE full_name = 'SHAVA AULIA WAHYUDI' AND class_name = '9E';
UPDATE public.students SET nisn = '0118128282', updated_at = NOW() WHERE full_name = 'SINTA SEFTIANI' AND class_name = '9E';
UPDATE public.students SET nisn = '0126446856', updated_at = NOW() WHERE full_name = 'SYIFA MAULIDATUL FITRIA' AND class_name = '9E';
UPDATE public.students SET nisn = '0127987664', updated_at = NOW() WHERE full_name = 'TUBAGUS FAEYZA MAJID' AND class_name = '9E';
UPDATE public.students SET nisn = '0127589272', updated_at = NOW() WHERE full_name = 'YOLANDA FITRIA' AND class_name = '9E';
UPDATE public.students SET nisn = '0126300851', updated_at = NOW() WHERE full_name = 'YULIANA SUCI WULANDARI' AND class_name = '9E';
UPDATE public.students SET nisn = '0127344720', updated_at = NOW() WHERE full_name = 'AULIA FAUZIAH' AND class_name = '9E';
UPDATE public.students SET nisn = '0122491639', updated_at = NOW() WHERE full_name = 'DARRY PUTRA DIGDAYA' AND class_name = '9E';
UPDATE public.students SET nisn = '0128478175', updated_at = NOW() WHERE full_name = 'AHYA''I AMWATULLAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0117815253', updated_at = NOW() WHERE full_name = 'ALIYA DITA ZAFIRA' AND class_name = '9F';
UPDATE public.students SET nisn = '0121795570', updated_at = NOW() WHERE full_name = 'AMIRA TYAS MARGONO' AND class_name = '9F';
UPDATE public.students SET nisn = '0124357273', updated_at = NOW() WHERE full_name = 'ARJUNA MAHARDIKA PRATAMA' AND class_name = '9F';
UPDATE public.students SET nisn = '0129712478', updated_at = NOW() WHERE full_name = 'AZZAHNY PUTRI HERMAWAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0113054857', updated_at = NOW() WHERE full_name = 'BRIAND JABBAR NOVANTO' AND class_name = '9F';
UPDATE public.students SET nisn = '3116033736', updated_at = NOW() WHERE full_name = 'DESWITA OKTADINA' AND class_name = '9F';
UPDATE public.students SET nisn = '0129459826', updated_at = NOW() WHERE full_name = 'EKA SULPATRI' AND class_name = '9F';
UPDATE public.students SET nisn = '0113374881', updated_at = NOW() WHERE full_name = 'FATURROHMAN SYAPUTRA' AND class_name = '9F';
UPDATE public.students SET nisn = '3126600498', updated_at = NOW() WHERE full_name = 'GALVIN ZAKY PRANIANSYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0123634987', updated_at = NOW() WHERE full_name = 'GINAA AAFIYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0129090902', updated_at = NOW() WHERE full_name = 'HASINA NAYYARA AL GHOJALI' AND class_name = '9F';
UPDATE public.students SET nisn = '0125082581', updated_at = NOW() WHERE full_name = 'JAHROTUN NAKIYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0121299696', updated_at = NOW() WHERE full_name = 'KANZA MAYDINA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '3123635819', updated_at = NOW() WHERE full_name = 'KAYLA UDZMA' AND class_name = '9F';
UPDATE public.students SET nisn = '0113695829', updated_at = NOW() WHERE full_name = 'KHOIRUL DWIANJAYA' AND class_name = '9F';
UPDATE public.students SET nisn = '0118313794', updated_at = NOW() WHERE full_name = 'LIA AULIA' AND class_name = '9F';
UPDATE public.students SET nisn = '0126889748', updated_at = NOW() WHERE full_name = 'LUSI AGUSTINA RHAMADANI' AND class_name = '9F';
UPDATE public.students SET nisn = '0117229418', updated_at = NOW() WHERE full_name = 'MAS ANANDA AZRIE MAULANA R' AND class_name = '9F';
UPDATE public.students SET nisn = '0124763210', updated_at = NOW() WHERE full_name = 'MAULIDIYA ASSIFA' AND class_name = '9F';
UPDATE public.students SET nisn = '0124817005', updated_at = NOW() WHERE full_name = 'MOHAMMAD FAKHRI AZHAR' AND class_name = '9F';
UPDATE public.students SET nisn = '0117928161', updated_at = NOW() WHERE full_name = 'MUHAMAD MAHESA AL-FIZAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0124204537', updated_at = NOW() WHERE full_name = 'MUHAMAD RHEZA RAMADHAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0125946267', updated_at = NOW() WHERE full_name = 'MUHAMMAD RIZKY RAMADAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0105864685', updated_at = NOW() WHERE full_name = 'NAURA SESILIA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '0123017640', updated_at = NOW() WHERE full_name = 'NESSYA FAHIRA MEGA' AND class_name = '9F';
UPDATE public.students SET nisn = '0121064027', updated_at = NOW() WHERE full_name = 'NUR HIKMAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0122908516', updated_at = NOW() WHERE full_name = 'OLIVIA DARA PUTRI' AND class_name = '9F';
UPDATE public.students SET nisn = '0127238199', updated_at = NOW() WHERE full_name = 'PUTRI RAHAYU' AND class_name = '9F';
UPDATE public.students SET nisn = '0123477533', updated_at = NOW() WHERE full_name = 'RAEYA SAABIRA GUNAWAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0119617448', updated_at = NOW() WHERE full_name = 'RISKA NATALIA SIMARMATA' AND class_name = '9F';
UPDATE public.students SET nisn = '0108044729', updated_at = NOW() WHERE full_name = 'SALSABILA SUHANAH' AND class_name = '9F';
UPDATE public.students SET nisn = '3121884450', updated_at = NOW() WHERE full_name = 'SEP RAHMAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0113292263', updated_at = NOW() WHERE full_name = 'SHIFA KHANSA AFIRA' AND class_name = '9F';
UPDATE public.students SET nisn = '0125580723', updated_at = NOW() WHERE full_name = 'SYAKIRA ALMIRA ZAHARANI' AND class_name = '9F';
UPDATE public.students SET nisn = '0127708158', updated_at = NOW() WHERE full_name = 'SYIFA CORDELIA RAFANI' AND class_name = '9F';
UPDATE public.students SET nisn = '0122901432', updated_at = NOW() WHERE full_name = 'VANESHA NOVIANATA' AND class_name = '9F';
UPDATE public.students SET nisn = '0127442757', updated_at = NOW() WHERE full_name = 'MUHAMMAD IZHAM ADRIANSYAH' AND class_name = '9F';
UPDATE public.students SET nisn = '3124538467', updated_at = NOW() WHERE full_name = 'ALMAY RAYYAN RUBY FALAH' AND class_name = '9F';
UPDATE public.students SET nisn = '0123971343', updated_at = NOW() WHERE full_name = 'AL BAIHAQI MARTIAN' AND class_name = '9F';
UPDATE public.students SET nisn = '0126291184', updated_at = NOW() WHERE full_name = 'ABDAN PARY' AND class_name = '9G';
UPDATE public.students SET nisn = '0123395587', updated_at = NOW() WHERE full_name = 'ALLONA PUTRI ZANETA' AND class_name = '9G';
UPDATE public.students SET nisn = '0125961844', updated_at = NOW() WHERE full_name = 'ANDIKA RIZKI FIRDAUS' AND class_name = '9G';
UPDATE public.students SET nisn = '0123442143', updated_at = NOW() WHERE full_name = 'ANISA RAMADANI' AND class_name = '9G';
UPDATE public.students SET nisn = '0118984552', updated_at = NOW() WHERE full_name = 'ASRA DIPA SURIYANTO' AND class_name = '9G';
UPDATE public.students SET nisn = '0118705770', updated_at = NOW() WHERE full_name = 'CHESTER ABIA RACHMAD' AND class_name = '9G';
UPDATE public.students SET nisn = '0126795110', updated_at = NOW() WHERE full_name = 'DHINA PUTRIANA' AND class_name = '9G';
UPDATE public.students SET nisn = '0129990784', updated_at = NOW() WHERE full_name = 'ELOISE MEGHAN PRANATA' AND class_name = '9G';
UPDATE public.students SET nisn = '0116455207', updated_at = NOW() WHERE full_name = 'FADHILAH AFZA NAIFA' AND class_name = '9G';
UPDATE public.students SET nisn = '0117427455', updated_at = NOW() WHERE full_name = 'FATIH ABDI BUDIMAN' AND class_name = '9G';
UPDATE public.students SET nisn = '0118963696', updated_at = NOW() WHERE full_name = 'FAZILA BELVA' AND class_name = '9G';
UPDATE public.students SET nisn = '0129687268', updated_at = NOW() WHERE full_name = 'FRISKA AFISTA AULIA' AND class_name = '9G';
UPDATE public.students SET nisn = '0123794629', updated_at = NOW() WHERE full_name = 'HAYATI NUFUS' AND class_name = '9G';
UPDATE public.students SET nisn = '0122917533', updated_at = NOW() WHERE full_name = 'JELITA ARYANTI PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '0124374937', updated_at = NOW() WHERE full_name = 'KARUNIA EKA NINGSIH' AND class_name = '9G';
UPDATE public.students SET nisn = '0122832226', updated_at = NOW() WHERE full_name = 'KEYLA AULIA PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '0115381344', updated_at = NOW() WHERE full_name = 'LAILATUL QOMARIAH' AND class_name = '9G';
UPDATE public.students SET nisn = '0125266213', updated_at = NOW() WHERE full_name = 'M. FEBRIYANSYAH' AND class_name = '9G';
UPDATE public.students SET nisn = '0113134833', updated_at = NOW() WHERE full_name = 'MARSHA OKTAVIA LATIFANISA' AND class_name = '9G';
UPDATE public.students SET nisn = '0128676406', updated_at = NOW() WHERE full_name = 'MICHAELA AZKIA ISLAMADINA' AND class_name = '9G';
UPDATE public.students SET nisn = '0129180890', updated_at = NOW() WHERE full_name = 'MOH IKBAR FAAD' AND class_name = '9G';
UPDATE public.students SET nisn = '0124807557', updated_at = NOW() WHERE full_name = 'MUHAMAD ADI FIRMANSYAH' AND class_name = '9G';
UPDATE public.students SET nisn = '0116011417', updated_at = NOW() WHERE full_name = 'MUHAMAD RAPAEL' AND class_name = '9G';
UPDATE public.students SET nisn = '0117128895', updated_at = NOW() WHERE full_name = 'MUHAMMAD IBNU AL-JABBAR' AND class_name = '9G';
UPDATE public.students SET nisn = '0116287409', updated_at = NOW() WHERE full_name = 'MUHAMMAD IHWANUL KARIM' AND class_name = '9G';
UPDATE public.students SET nisn = '0124889849', updated_at = NOW() WHERE full_name = 'NABIL ATHA SAKHI' AND class_name = '9G';
UPDATE public.students SET nisn = '0116456328', updated_at = NOW() WHERE full_name = 'NEYSA AYU DESTIANA' AND class_name = '9G';
UPDATE public.students SET nisn = '3121348414', updated_at = NOW() WHERE full_name = 'NIKEN APRILIANI' AND class_name = '9G';
UPDATE public.students SET nisn = '0119887036', updated_at = NOW() WHERE full_name = 'REGITA CAHYANI' AND class_name = '9G';
UPDATE public.students SET nisn = '3126826923', updated_at = NOW() WHERE full_name = 'RIZKI AL SEBASTIAN' AND class_name = '9G';
UPDATE public.students SET nisn = '0116859301', updated_at = NOW() WHERE full_name = 'RIZKI MAULANA SOPIAN' AND class_name = '9G';
UPDATE public.students SET nisn = '0123406631', updated_at = NOW() WHERE full_name = 'SANTI KURNIAWATI' AND class_name = '9G';
UPDATE public.students SET nisn = '3128699121', updated_at = NOW() WHERE full_name = 'SHAALIHUDDIN AL-AYUBI' AND class_name = '9G';
UPDATE public.students SET nisn = '3117521079', updated_at = NOW() WHERE full_name = 'SRI ULYATI' AND class_name = '9G';
UPDATE public.students SET nisn = '0129179041', updated_at = NOW() WHERE full_name = 'SYAUQI JALADARA PUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '0115266483', updated_at = NOW() WHERE full_name = 'TAHTA DHIKA SINATRIA' AND class_name = '9G';
UPDATE public.students SET nisn = '0124812866', updated_at = NOW() WHERE full_name = 'VICKY REVALKA ALKHI' AND class_name = '9G';
UPDATE public.students SET nisn = '0114653482', updated_at = NOW() WHERE full_name = 'VONDRA KASIH RIZKIA DETHAN' AND class_name = '9G';
UPDATE public.students SET nisn = '0116982436', updated_at = NOW() WHERE full_name = 'ZAHRA FITRIA SARI' AND class_name = '9G';
UPDATE public.students SET nisn = '0117841505', updated_at = NOW() WHERE full_name = 'DESTIANA SAPUTRI' AND class_name = '9G';
UPDATE public.students SET nisn = '0116203684', updated_at = NOW() WHERE full_name = 'MUHAMAD RIDO' AND class_name = '9G';
UPDATE public.students SET nisn = '0114257880', updated_at = NOW() WHERE full_name = 'ABDUL FAQRY' AND class_name = '9H';
UPDATE public.students SET nisn = '0115601261', updated_at = NOW() WHERE full_name = 'ACHMAD FARIZKY' AND class_name = '9H';
UPDATE public.students SET nisn = '0115123146', updated_at = NOW() WHERE full_name = 'AJENG PAMUNGKAS' AND class_name = '9H';
UPDATE public.students SET nisn = '0118338879', updated_at = NOW() WHERE full_name = 'ALMIRA IRGI BILQIST' AND class_name = '9H';
UPDATE public.students SET nisn = '0111779074', updated_at = NOW() WHERE full_name = 'ANDIKA GALANG RAMADHAN' AND class_name = '9H';
UPDATE public.students SET nisn = '0128422131', updated_at = NOW() WHERE full_name = 'APRILIA' AND class_name = '9H';
UPDATE public.students SET nisn = '0122980800', updated_at = NOW() WHERE full_name = 'AQILNABIGH PUTRA RAHMAN' AND class_name = '9H';
UPDATE public.students SET nisn = '0122976226', updated_at = NOW() WHERE full_name = 'ASYIFA RAMADHANI HAFID' AND class_name = '9H';
UPDATE public.students SET nisn = '3110171468', updated_at = NOW() WHERE full_name = 'CITRA FAHIRA' AND class_name = '9H';
UPDATE public.students SET nisn = '0122647056', updated_at = NOW() WHERE full_name = 'DHINI PUTRIANI' AND class_name = '9H';
UPDATE public.students SET nisn = '0121313467', updated_at = NOW() WHERE full_name = 'ELVINA REZKYA P' AND class_name = '9H';
UPDATE public.students SET nisn = '0118401282', updated_at = NOW() WHERE full_name = 'FATIMATUL ZAHRO' AND class_name = '9H';
UPDATE public.students SET nisn = '0129057761', updated_at = NOW() WHERE full_name = 'FAUZUL AMARULLAH' AND class_name = '9H';
UPDATE public.students SET nisn = '0128086971', updated_at = NOW() WHERE full_name = 'FEISYA AULIA ALMAS' AND class_name = '9H';
UPDATE public.students SET nisn = '0121029063', updated_at = NOW() WHERE full_name = 'GANESH AZALIA GAYATRI' AND class_name = '9H';
UPDATE public.students SET nisn = '0116273142', updated_at = NOW() WHERE full_name = 'KALFAN DANAR IBRAHIM' AND class_name = '9H';
UPDATE public.students SET nisn = '3128305922', updated_at = NOW() WHERE full_name = 'MANDALIKA CAHYA PUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '0123937054', updated_at = NOW() WHERE full_name = 'MERLY MUTIARA' AND class_name = '9H';
UPDATE public.students SET nisn = '0115695071', updated_at = NOW() WHERE full_name = 'MOHAMAD RAFA EMERALDIANTO' AND class_name = '9H';
UPDATE public.students SET nisn = '0129457706', updated_at = NOW() WHERE full_name = 'MUH RAFA RAMDANI' AND class_name = '9H';
UPDATE public.students SET nisn = '0117459722', updated_at = NOW() WHERE full_name = 'MUHAMAD AL GHAZALI' AND class_name = '9H';
UPDATE public.students SET nisn = '0117133193', updated_at = NOW() WHERE full_name = 'MUHAMAD FARHAN TRIDARMA' AND class_name = '9H';
UPDATE public.students SET nisn = '0121752842', updated_at = NOW() WHERE full_name = 'MUHAMAD KHA KURNIAWAN' AND class_name = '9H';
UPDATE public.students SET nisn = '0114210397', updated_at = NOW() WHERE full_name = 'MUHAMAD RAFQI RAMADHAN' AND class_name = '9H';
UPDATE public.students SET nisn = '0121312438', updated_at = NOW() WHERE full_name = 'MUHAMAD RAZKA IRSYA PRATAMA' AND class_name = '9H';
UPDATE public.students SET nisn = '3138508943', updated_at = NOW() WHERE full_name = 'MUHAMAD ZAKI ALHAFIDZ' AND class_name = '9H';
UPDATE public.students SET nisn = '0119214833', updated_at = NOW() WHERE full_name = 'MUHAMMAD RAFA SAEFUL' AND class_name = '9H';
UPDATE public.students SET nisn = '0125068493', updated_at = NOW() WHERE full_name = 'MUHAMMAD RICO ALFIAN' AND class_name = '9H';
UPDATE public.students SET nisn = '0112196130', updated_at = NOW() WHERE full_name = 'NADHIRA RAYSA SARAH' AND class_name = '9H';
UPDATE public.students SET nisn = '3118012004', updated_at = NOW() WHERE full_name = 'NAJWA ANANDA PUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '0126795093', updated_at = NOW() WHERE full_name = 'NIVA NIRVANA ZAFIRA' AND class_name = '9H';
UPDATE public.students SET nisn = '0113860611', updated_at = NOW() WHERE full_name = 'PUTRI GENDIS NOVIAUTAMI' AND class_name = '9H';
UPDATE public.students SET nisn = '0124209710', updated_at = NOW() WHERE full_name = 'RATU AURELIA ANEIRA RAIHANAH' AND class_name = '9H';
UPDATE public.students SET nisn = '0115044299', updated_at = NOW() WHERE full_name = 'RD.M SAID YUSUP' AND class_name = '9H';
UPDATE public.students SET nisn = '0112137379', updated_at = NOW() WHERE full_name = 'RENADA HANIFAH' AND class_name = '9H';
UPDATE public.students SET nisn = '3127431309', updated_at = NOW() WHERE full_name = 'RIFKI ADRIANSYAH' AND class_name = '9H';
UPDATE public.students SET nisn = '3129531251', updated_at = NOW() WHERE full_name = 'SAFIRA ANGRAENI' AND class_name = '9H';
UPDATE public.students SET nisn = '0112529516', updated_at = NOW() WHERE full_name = 'SATRIA MAULANA' AND class_name = '9H';
UPDATE public.students SET nisn = '0116193724', updated_at = NOW() WHERE full_name = 'SINTA WULAN SAPUTRI' AND class_name = '9H';
UPDATE public.students SET nisn = '0103319302', updated_at = NOW() WHERE full_name = 'SUCI DWI PURWANTI' AND class_name = '9H';
UPDATE public.students SET nisn = '0111643765', updated_at = NOW() WHERE full_name = 'TEDAS AWAN TANTULAR' AND class_name = '9H';
UPDATE public.students SET nisn = '0119330180', updated_at = NOW() WHERE full_name = 'ZAHRA SEPTIANI PUTRI' AND class_name = '9H';