-- ====================================================================
-- MIGRATION 003: SEED 246 STUDENTS (YEAR 2026/2027, NISN = NULL)
-- ====================================================================

DO $$
DECLARE
    rec RECORD;
    v_type RECORD;
    v_year TEXT := '2026/2027';
    v_year_slug TEXT := '2026-2027';
BEGIN
    -- Temporary staging table for raw student seeding
    CREATE TEMP TABLE tmp_seed_students (
        class_name TEXT NOT NULL,
        full_name TEXT NOT NULL
    ) ON COMMIT DROP;

    -- 7E (40 Siswa)
    INSERT INTO tmp_seed_students (class_name, full_name) VALUES
    ('7E', 'ABIDZAR PUTRA YOGI'),
    ('7E', 'ABIYYU EMIRUL KHAIR'),
    ('7E', 'ACQUILA AZZALEA QISYA'),
    ('7E', 'AFIQA HAMIDAH'),
    ('7E', 'ALPIAN MUHAMAD RAPA'),
    ('7E', 'ANINDIA RABIA PUTRI'),
    ('7E', 'AQILA AZIZATUL FADHLA'),
    ('7E', 'ARAFAH PUTRAYANA ADITYA'),
    ('7E', 'ARJUNA PRATAMA AKBAR'),
    ('7E', 'AYESHA HEBA ASSYAKIRA'),
    ('7E', 'AZKA MAULANA ARRAIHAN'),
    ('7E', 'CAPRILIA XANZA'),
    ('7E', 'CINTA NAURA SECHAN'),
    ('7E', 'DARPATUL LAILA RAHMADANI'),
    ('7E', 'DIMAS PRASONGKO'),
    ('7E', 'FADYA ASSYIFA'),
    ('7E', 'HAMDUN ABDUL KARIM'),
    ('7E', 'IFFA ASTILA RAHMA'),
    ('7E', 'KHANZA SHAZIA RIFA'),
    ('7E', 'KHAYURA ASYABIYA RAHMAN'),
    ('7E', 'KHOIRUNISA'),
    ('7E', 'MUHAMAD FILAN BAIHAKI'),
    ('7E', 'MUHAMAD REHAN ARIYAN'),
    ('7E', 'MUHAMAD RIZKY AL-QOWI'),
    ('7E', 'MUHAMMAD AFKAR ALQISTHI'),
    ('7E', 'MUHAMMAD AKMAL FALLAH'),
    ('7E', 'MUHAMMAD DIRGHAM HAIDAR NUGRAHA'),
    ('7E', 'MUHAMMAD RIZKY MAULANA'),
    ('7E', 'MUHAMMAD SAUGI AL-GHIFARI'),
    ('7E', 'NAJWA A''ISYATUL AFIFAH'),
    ('7E', 'NASYAH AGUSTINA'),
    ('7E', 'NAURA NADHIFA MALADI'),
    ('7E', 'NAYLA NEHAYATUL KAMILAH'),
    ('7E', 'PARULIAN LEE SIAHAAN'),
    ('7E', 'RAIHAN ALFA RISKI'),
    ('7E', 'RIANGGUN HAERUTAMA'),
    ('7E', 'RIKO DUTA DAMARA'),
    ('7E', 'SABINA AYLA QAIREEN'),
    ('7E', 'SIPA ALISA AJAHRA'),
    ('7E', 'ZIANDRA NAZMU NUGRAHA'),

    -- 7F (40 Siswa)
    ('7F', 'AKHMAD JEN'),
    ('7F', 'AKILLA DESFINDA'),
    ('7F', 'AKSA ALHAFIZH MARGONO'),
    ('7F', 'AMARA NABILA ZAKIA'),
    ('7F', 'ANGEL HABIBAH'),
    ('7F', 'AQILA SASABILA RAMADHANI'),
    ('7F', 'AULIYA ARISTA FIRDIYANA'),
    ('7F', 'AZKHA MAULANA'),
    ('7F', 'BILQIS UFAIRA'),
    ('7F', 'CANTIKA KAYLA PUTRI'),
    ('7F', 'DIKI MAULANA FAUZAN'),
    ('7F', 'DZAKI SURYA MAHESA'),
    ('7F', 'ERINDA FAZYLA SUSANTO'),
    ('7F', 'FAIQ RAFIQI NURA'),
    ('7F', 'FARHAN SEPTIYANI'),
    ('7F', 'FARIZ NAUFAL RAHARDIAN'),
    ('7F', 'FAUZIYAH'),
    ('7F', 'HANIFAIHA RAMADHANI'),
    ('7F', 'HANY RIZKIYA'),
    ('7F', 'KENZY ASSYIFA MAGHDALENA'),
    ('7F', 'M.ZHILDAN RAMADHAN'),
    ('7F', 'MEISHADIVIA SANTOSO'),
    ('7F', 'MUHAMMAD AQLAN RHOMDONY'),
    ('7F', 'MUHAMMAD AZZAM MAJIID SANTOSO'),
    ('7F', 'MUHAMMAD FATHIR MAULANA'),
    ('7F', 'MUHAMMAD FATIR AS-SYAQIR'),
    ('7F', 'MUHAMMAD HASURI'),
    ('7F', 'MUHAMMAD JABIL RUSYAIDI'),
    ('7F', 'MUHAMMAD JULIANSAH'),
    ('7F', 'MUHAMMAD SYUJA'),
    ('7F', 'NAURA SHAFWAN MASITA'),
    ('7F', 'RAFELLA RAISHA'),
    ('7F', 'RATU ADZKIARA VAHLEVI'),
    ('7F', 'RATU NAFISAH ELZHAR'),
    ('7F', 'RIFAL AKBAR'),
    ('7F', 'RISKA RAMADANI'),
    ('7F', 'ROBIATUL ADAWIYAH APDI'),
    ('7F', 'SALSA NABILA JUANDINI'),
    ('7F', 'SANDY'),
    ('7F', 'SATRIO SANTOSO'),

    -- 9E (42 Siswa)
    ('9E', 'ABDUL SAHID'),
    ('9E', 'AHMAD FAUZAN SHOFA'),
    ('9E', 'AHMAD SABIL AUFA'),
    ('9E', 'ALISHBA NAYYARA FILZAH'),
    ('9E', 'ARYA DZAKY NATAKUSUMAH'),
    ('9E', 'ATIKAH RAMADANI'),
    ('9E', 'AZWAN SYAHRIL FAUJI'),
    ('9E', 'BILAL ATHAR'),
    ('9E', 'CHARISSA GALUH BACHTIAR'),
    ('9E', 'DANI ARDIANSYAH'),
    ('9E', 'FAHRY AHMAD'),
    ('9E', 'FAQIH RAMADHAN'),
    ('9E', 'FAUZAN AVIAN MUNIR'),
    ('9E', 'KHOLIFAH MEYLANI PUTRI'),
    ('9E', 'LINTANG NAGA CAESAR'),
    ('9E', 'LISDA NINGSIH RAMADHANI'),
    ('9E', 'MUHAMAD FADHIL LUKMAN'),
    ('9E', 'MUHAMAD ILYAS DZULKARNAIN'),
    ('9E', 'MUHAMAD WILDAN SEBASTIAN'),
    ('9E', 'MUHAMMAD FARIS MULYAWAN'),
    ('9E', 'MUHAMMAD KHAIRUL FAHMI'),
    ('9E', 'MUHAMMAD MIRZA ARIFIN'),
    ('9E', 'MUHAMMAD RADITHYA PRATAMA RONIE'),
    ('9E', 'MUHAMMAD RAFLY MAULANA'),
    ('9E', 'NAURA BELLA'),
    ('9E', 'NISA ULPA DILA'),
    ('9E', 'NOVA AZZAHRA'),
    ('9E', 'RAMA FAHRURROZI'),
    ('9E', 'RATU PARAMITA ANANTA'),
    ('9E', 'RAYA RIZQINA RAMADHANI'),
    ('9E', 'RENAFA DWI CAHYANI'),
    ('9E', 'RIFDA MUHNINA PUTRI'),
    ('9E', 'SADIRA KASYIFAQILA TRIADI'),
    ('9E', 'SALLY KIRANA APRILIA SIREGAR'),
    ('9E', 'SHAVA AULIA WAHYUDI'),
    ('9E', 'SINTA SEFTIANI'),
    ('9E', 'SYIFA MAULIDATUL FITRIA'),
    ('9E', 'TUBAGUS FAEYZA MAJID'),
    ('9E', 'YOLANDA FITRIA'),
    ('9E', 'YULIANA SUCI WULANDARI'),
    ('9E', 'AULIA FAUZIAH'),
    ('9E', 'DARRY PUTRA DIGDAYA'),

    -- 9F (41 Siswa)
    ('9F', 'AHYA''I AMWATULLAH'),
    ('9F', 'ALIYA DITA ZAFIRA'),
    ('9F', 'AMIRA TYAS MARGONO'),
    ('9F', 'ARJUNA MAHARDIKA PRATAMA'),
    ('9F', 'AZZAHNY PUTRI HERMAWAN'),
    ('9F', 'BRIAND JABBAR NOVANTO'),
    ('9F', 'DESWITA OKTADINA'),
    ('9F', 'EKA SULPATRI'),
    ('9F', 'FATURROHMAN SYAPUTRA'),
    ('9F', 'FERDY ADITIYA'),
    ('9F', 'GALVIN ZAKY PRANIANSYAH'),
    ('9F', 'GINAA AAFIYAH'),
    ('9F', 'HASINA NAYYARA AL GHOJALI'),
    ('9F', 'JAHROTUN NAKIYAH'),
    ('9F', 'KANZA MAYDINA PUTRI'),
    ('9F', 'KAYLA UDZMA'),
    ('9F', 'KHOIRUL DWIANJAYA'),
    ('9F', 'LIA AULIA'),
    ('9F', 'LUSI AGUSTINA RHAMADANI'),
    ('9F', 'MAS ANANDA AZRIE MAULANA R'),
    ('9F', 'MAULIDIYA ASSIFA'),
    ('9F', 'MOHAMMAD FAKHRI AZHAR'),
    ('9F', 'MUHAMAD MAHESA AL-FIZAN'),
    ('9F', 'MUHAMAD RHEZA RAMADHAN'),
    ('9F', 'MUHAMMAD RIZKY RAMADAN'),
    ('9F', 'NAURA SESILIA PUTRI'),
    ('9F', 'NESSYA FAHIRA MEGA'),
    ('9F', 'NUR HIKMAH'),
    ('9F', 'OLIVIA DARA PUTRI'),
    ('9F', 'PUTRI RAHAYU'),
    ('9F', 'RAEYA SAABIRA GUNAWAN'),
    ('9F', 'RISKA NATALIA SIMARMATA'),
    ('9F', 'SALSABILA SUHANAH'),
    ('9F', 'SEP RAHMAN'),
    ('9F', 'SHIFA KHANSA AFIRA'),
    ('9F', 'SYAKIRA ALMIRA ZAHARANI'),
    ('9F', 'SYIFA CORDELIA RAFANI'),
    ('9F', 'VANESHA NOVIANATA'),
    ('9F', 'MUHAMMAD IZHAM ADRIANSYAH'),
    ('9F', 'ALMAY RAYYAN RUBY FALAH'),
    ('9F', 'AL BAIHAQI MARTIAN'),

    -- 9G (41 Siswa)
    ('9G', 'ABDAN PARY'),
    ('9G', 'ALLONA PUTRI ZANETA'),
    ('9G', 'ANDIKA RIZKI FIRDAUS'),
    ('9G', 'ANISA RAMADANI'),
    ('9G', 'ASRA DIPA SURIYANTO'),
    ('9G', 'CHESTER ABIA RACHMAD'),
    ('9G', 'DHINA PUTRIANA'),
    ('9G', 'ELOISE MEGHAN PRANATA'),
    ('9G', 'FADHILAH AFZA NAIFA'),
    ('9G', 'FATIH ABDI BUDIMAN'),
    ('9G', 'FAZILA BELVA'),
    ('9G', 'FRISKA AFISTA AULIA'),
    ('9G', 'HAYATI NUFUS'),
    ('9G', 'JELITA ARYANTI PUTRI'),
    ('9G', 'KARUNIA EKA NINGSIH'),
    ('9G', 'KEYLA AULIA PUTRI'),
    ('9G', 'LAILATUL QOMARIAH'),
    ('9G', 'M. FEBRIYANSYAH'),
    ('9G', 'MARSHA OKTAVIA LATIFANISA'),
    ('9G', 'MICHAELA AZKIA ISLAMADINA'),
    ('9G', 'MOH IKBAR FAAD'),
    ('9G', 'MUHAMAD ADI FIRMANSYAH'),
    ('9G', 'MUHAMAD RAPAEL'),
    ('9G', 'MUHAMMAD IBNU AL-JABBAR'),
    ('9G', 'MUHAMMAD IHWANUL KARIM'),
    ('9G', 'NABIL ATHA SAKHI'),
    ('9G', 'NEYSA AYU DESTIANA'),
    ('9G', 'NIKEN APRILIANI'),
    ('9G', 'REGITA CAHYANI'),
    ('9G', 'RIZKI AL SEBASTIAN'),
    ('9G', 'RIZKI MAULANA SOPIAN'),
    ('9G', 'SANTI KURNIAWATI'),
    ('9G', 'SHAALIHUDDIN AL-AYUBI'),
    ('9G', 'SRI ULYATI'),
    ('9G', 'SYAUQI JALADARA PUTRI'),
    ('9G', 'TAHTA DHIKA SINATRIA'),
    ('9G', 'VICKY REVALKA ALKHI'),
    ('9G', 'VONDRA KASIH RIZKIA DETHAN'),
    ('9G', 'ZAHRA FITRIA SARI'),
    ('9G', 'DESTIANA SAPUTRI'),
    ('9G', 'MUHAMAD RIDO'),

    -- 9H (42 Siswa)
    ('9H', 'ABDUL FAQRY'),
    ('9H', 'ACHMAD FARIZKY'),
    ('9H', 'AJENG PAMUNGKAS'),
    ('9H', 'ALMIRA IRGI BILQIST'),
    ('9H', 'ANDIKA GALANG RAMADHAN'),
    ('9H', 'APRILIA'),
    ('9H', 'AQILNABIGH PUTRA RAHMAN'),
    ('9H', 'ASYIFA RAMADHANI HAFID'),
    ('9H', 'CITRA FAHIRA'),
    ('9H', 'DHINI PUTRIANI'),
    ('9H', 'ELVINA REZKYA P'),
    ('9H', 'FATIMATUL ZAHRO'),
    ('9H', 'FAUZUL AMARULLAH'),
    ('9H', 'FEISYA AULIA ALMAS'),
    ('9H', 'GANESH AZALIA GAYATRI'),
    ('9H', 'KALFAN DANAR IBRAHIM'),
    ('9H', 'MANDALIKA CAHYA PUTRI'),
    ('9H', 'MERLY MUTIARA'),
    ('9H', 'MOHAMAD RAFA EMERALDIANTO'),
    ('9H', 'MUH RAFA RAMDANI'),
    ('9H', 'MUHAMAD AL GHAZALI'),
    ('9H', 'MUHAMAD FARHAN TRIDARMA'),
    ('9H', 'MUHAMAD KHA KURNIAWAN'),
    ('9H', 'MUHAMAD RAFQI RAMADHAN'),
    ('9H', 'MUHAMAD RAZKA IRSYA PRATAMA'),
    ('9H', 'MUHAMAD ZAKI ALHAFIDZ'),
    ('9H', 'MUHAMMAD RAFA SAEFUL'),
    ('9H', 'MUHAMMAD RICO ALFIAN'),
    ('9H', 'NADHIRA RAYSA SARAH'),
    ('9H', 'NAJWA ANANDA PUTRI'),
    ('9H', 'NIVA NIRVANA ZAFIRA'),
    ('9H', 'PUTRI GENDIS NOVIAUTAMI'),
    ('9H', 'RATU AURELIA ANEIRA RAIHANAH'),
    ('9H', 'RD.M SAID YUSUP'),
    ('9H', 'RENADA HANIFAH'),
    ('9H', 'RIFKI ADRIANSYAH'),
    ('9H', 'SAFIRA ANGRAENI'),
    ('9H', 'SATRIA MAULANA'),
    ('9H', 'SINTA WULAN SAPUTRI'),
    ('9H', 'SUCI DWI PURWANTI'),
    ('9H', 'TEDAS AWAN TANTULAR'),
    ('9H', 'ZAHRA SEPTIANI PUTRI');

    -- Insert students with unique UUIDs and NULL NISN
    FOR rec IN SELECT class_name, full_name FROM tmp_seed_students LOOP
        -- Insert or retrieve student
        INSERT INTO public.students (full_name, class_name, school_year, nisn, pin_hash, pin_salt, is_active)
        VALUES (rec.full_name, rec.class_name, v_year, NULL, NULL, NULL, true)
        ON CONFLICT DO NOTHING;
    END LOOP;

    -- Create initial assessment_files placeholder for every student & assessment type
    FOR rec IN SELECT id, class_name FROM public.students WHERE school_year = v_year LOOP
        FOR v_type IN SELECT id, slug, filename FROM public.assessment_types WHERE is_active = true LOOP
            INSERT INTO public.assessment_files (
                student_id,
                assessment_type_id,
                storage_path,
                original_filename,
                is_available
            )
            VALUES (
                rec.id,
                v_type.id,
                v_year_slug || '/' || rec.class_name || '/' || rec.id || '/' || v_type.filename,
                v_type.filename,
                false
            )
            ON CONFLICT (student_id, assessment_type_id) DO NOTHING;
        END LOOP;
    END LOOP;

END $$;
